info:
  version: 1.0.0
  description: E2Node initial configuration

configuration:
  e2NodeName: E2Node # the name of this E2Node
  ricAddress: # the address of the RIC
    - 192.168.17.125 # RIC address
  ricPort: 32222 #36422 #36412 # the port of the RIC
  localAddress: # the local address to bind to
    - 192.168.17.93
  # HTTP endpoint used by the RC callbacks to trigger N3IWF handover.
  # If set, this overrides the builtâ€‘in default and the RC code will
  # send POST /rc/handover to this URL.
  n3iwfHandoverUrl: "http://192.168.17.94:9085/rc/handover"
  gnbCuUpId: 2
   # gNB CU-UP ID to be used in E2AP messages
  gnbDuId: 2
   # gNB DU ID to be used in E2AP messages